<?php

namespace FlexiAPI\Endpoints;

use FlexiAPI\Core\BaseEndpointController;
use FlexiAPI\Utils\Response;
use FlexiAPI\Utils\Validator;

/**
 * UsersController - Auto-generated by FlexiAPI CLI
 * Endpoint: /users
 * Generated on: 2025-10-12 17:09:43
 */
class UsersController extends BaseEndpointController
{
    protected string $tableName = 'users';
    protected array $fillable = ['Name', 'Age', 'Gender'];

    protected function getValidationRules(): array
    {
        return [
            'Name' => '',
            'Age' => '',
            'Gender' => '',
        ];
    }

    // Add custom methods here
}
