<?php

// Routes for users endpoint
// Auto-generated by FlexiAPI CLI on 2025-10-12 17:09:43

use FlexiAPI\Endpoints\UsersController;

$controller = new UsersController($db, $config);

// REST endpoints for users
$router->get('/users', function() use ($controller) {
    $controller->index();
});

$router->post('/users', function() use ($controller) {
    $controller->store();
});

$router->get('/users/{id}', function($id) use ($controller) {
    $controller->show($id);
});

$router->put('/users/{id}', function($id) use ($controller) {
    $controller->update($id);
});

$router->delete('/users/{id}', function($id) use ($controller) {
    $controller->destroy($id);
});
